# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT License"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/jdawg3636/ICBM/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="icbm" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

 # A display name for the mod
displayName="ICBM" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://icbm.jdawg3636.com/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icbm_logo.png" #optional

# A text field displayed in the mod UI (#optional)
credits='''

jdawg3636 (Author ICBM Reborn)
DarkGuardsman (Author ICBM Classic)
Calcalvia (Author ICBM)
tgame14
bl4ckscor3
GHXX
dmodoomsirius
AFlyingCar
clienthax
kmecpp
Quant1um
suoliangao
CraftalotReloaded
michasrutek
gravityfox
Vexatos
Nowp
Hennamann
Bogdan2003
'''

# A text field displayed in the mod UI
authors="jdawg3636" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
ICBM is a Minecraft Mod that introduces intercontinental ballistic missiles to Minecraft.
But the fun doesn't end there! This mod also features many different explosives, missiles and machines
classified in three different tiers. If strategic warfare, carefully coordinated airstrikes, messing
with matter and general destruction are up your alley, then this mod is for you!
'''
